server {
    listen 80;
    server_name localhost;

    location /rss-app {
        alias /usr/share/nginx/html/rss-app;
        index index.html index.htm;
        try_files $uri $uri/ /rss-app/index.html;
        
        include /etc/nginx/mime.types;
    }

    # Redirect root to /rss-app/
    location = / {
        return 301 /rss-app/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
